# Generated by Django 4.0.5 on 2022-07-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Расположение', 'verbose_name_plural': 'Расположения'},
        ),
    ]
